language: node_js
sudo: false
node_js:
  - "0.10.38"
env:
  global:
    - LOG_LEVEL=none
    - LOG_LEVEL_STDOUT=error
services:
  - mongodb
  - redis-server
  - rabbitmq
before_install:
  - ulimit -n
  - npm install -g npm@2.8.3
  - wget http://neo4j.com/artifact.php?name=neo4j-community-2.1.8-unix.tar.gz -O /tmp/neo4j-community-2.1.8-unix.tar.gz
  - cd /tmp; tar -xzvf neo4j-community-2.1.8-unix.tar.gz; cd -
  - /tmp/neo4j-community-2.1.8/bin/neo4j start
  - ./scripts/set-neo4j-constraint.sh
script:
  - npm run lint
  - npm run unit
  - npm run bdd
