language: node_js
sudo: false
node_js:
  - "0.10.38"
matrix:
  fast_finish: true
env:
  global:
    - LOG_LEVEL=none
    - LOG_LEVEL_STDOUT=error
    - CIRCLE_NODE_TOTAL=2
  matrix:
    - CIRCLE_NODE_INDEX=0
    - CIRCLE_NODE_INDEX=1
cache:
  - directories:
    - /tmp/neo4j-community-2.1.8
before_cache:
  - rm -rf /tmp/neo4j-community-2.1.8/data/graph.db
services:
  - mongodb
  - redis-server
  - rabbitmq
before_install:
  - ulimit -n
  - npm install -g npm@2.8.3
  - ./scripts/download-neo4j.sh
  - /tmp/neo4j-community-2.1.8/bin/neo4j start
  - timeout 1m ./scripts/set-neo4j-constraint.sh
script:
  - timeout 10m ./scripts/npm-bdd-split-files.sh
