language: node_js
sudo: false
node_js:
- 4.2.2
matrix:
  fast_finish: true
env:
  global:
  - LOG_LEVEL=trace
  - CIRCLE_NODE_TOTAL=3
  matrix:
  - CIRCLE_NODE_INDEX=0
  - CIRCLE_NODE_INDEX=1
  - CIRCLE_NODE_INDEX=2
cache:
- directories:
  - /tmp/downloads
  - ./node_modules
services:
- mongodb
- redis-server
- rabbitmq
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
- ulimit -n
- npm install -g npm@2.8.3
before_script:
- npm run lint
script:
- timeout 3m ./scripts/run-command-conditionally.sh npm run unit
- timeout 15m ./scripts/npm-bdd-split-files.sh
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: Q8OJnQnA0a7pbVBOxwjOGhrwDXPkSGODndxFdeNI3Pfi2qgV+8AE/vJvKRlOw4Dv5BshdCD8ObAd4rU+bwjpRNt81fL7taIssOZ8YyeE34FAqo/ykLUXdIliuVWoCuT0H+OWKkSAhp6ltCG4rXOAUfuowUfb0d031YRWiu22jiI=
