language: node_js
sudo: false
node_js:
- 0.10.38
matrix:
  fast_finish: true
env:
  global:
  - LOG_LEVEL_STDOUT=fatal
  - CIRCLE_NODE_TOTAL=3
  matrix:
  - CIRCLE_NODE_INDEX=0
  - CIRCLE_NODE_INDEX=1
  - CIRCLE_NODE_INDEX=2
cache:
- directories:
  - /tmp/downloads
  - ./node_modules
services:
- mongodb
- redis-server
- rabbitmq
before_install:
- ulimit -n
- npm install -g npm@2.8.3
- ./scripts/download-neo4j.sh
- /tmp/neo4j-community-2.1.8/bin/neo4j start
- timeout 1m ./scripts/set-neo4j-constraint.sh
before_script:
- npm run lint
script:
- timeout 10m npm run bdd-whitelist
after_script:
- /tmp/neo4j-community-2.1.8/bin/neo4j stop
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: Q8OJnQnA0a7pbVBOxwjOGhrwDXPkSGODndxFdeNI3Pfi2qgV+8AE/vJvKRlOw4Dv5BshdCD8ObAd4rU+bwjpRNt81fL7taIssOZ8YyeE34FAqo/ykLUXdIliuVWoCuT0H+OWKkSAhp6ltCG4rXOAUfuowUfb0d031YRWiu22jiI=
