language: node_js
node_js:
  - "0.10.38"
env:
  global:
    - CIRCLE_NODE_TOTAL=2
  matrix:
    - CIRCLE_NODE_INDEX=0
    - CIRCLE_NODE_INDEX=1
services:
  - mongodb
  - redis-server
  - rabbitmq
before_install:
  - ulimit -n
  - npm install -g npm@2.8.3
  - wget http://neo4j.com/artifact.php?name=neo4j-community-2.1.8-unix.tar.gz -O /tmp/neo4j-community-2.1.8-unix.tar.gz
  - cd /tmp; tar -xzvf neo4j-community-2.1.8-unix.tar.gz; cd -
  - /tmp/neo4j-community-2.1.8/bin/neo4j start
  - curl 127.0.0.1:7474/db/data/
script:
  - npm run lint
  - npm run unit
  - npm run bdd
