# Full list of versions available here: https://registry.hub.docker.com/_/node/tags/manage/\n' +
FROM node:4.6.1

ENV NPM_TOKEN=c76363e9-78e0-4667-82ac-e2ac01efcfe2

#Start: Main Repository
ADD [".", "/api"]
WORKDIR /api
RUN npm set strict-ssl false
RUN echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
RUN npm install

#End

WORKDIR /api

CMD npm run unit
