version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_unit_test
    links:
      - 'redis'
    environment:
      - REDIS_IPADDRESS=redis
  redis:
    image: redis:3.2
