version: '2'
services:
  bdd:
    build:
      context: .
      dockerfile: Dockerfile_bdd_test
    links:
      - 'rabbit-bdd'
      - 'redis-bdd'
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOSTNAME=rabbit-bdd
      - MONGO=mongodb://localhost:27017/runnable_test
      - REDIS_IPADDRESS=redis-bdd
  unit:
    build:
      context: .
      dockerfile: Dockerfile_unit_test
    links:
      - 'redis-unit'
    environment:
      - REDIS_IPADDRESS=redis-unit
  rabbit-bdd:
    image: rabbitmq:3.4.3-management
  redis-bdd:
    image: redis:3.2
  redis-unit:
    image: redis:3.2
