FROM node:argon

RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /wait.sh
RUN chmod +x /wait.sh

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
RUN apt-get update
RUN apt-get install -y mongodb-10gen=2.4.12
RUN mkdir -p /data/db/

ENV NPM_TOKEN=c76363e9-78e0-4667-82ac-e2ac01efcfe2

ADD ./keys/runnable-deploy-bot.id_rsa /root/.ssh/id_rsa
WORKDIR /root/.ssh/
RUN chmod 0400 id_rsa && echo "IdentityFile /root/.ssh/id_rsa" >> /etc/ssh/ssh_config && ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts

ADD ./package.json /api/package.json
WORKDIR /api
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
RUN npm install

ADD ./ /api

EXPOSE 3000

CMD /wait.sh rabbit_bdd:5672 -t 60 && /wait.sh redis_bdd:6379 && mongod --fork --logpath /var/log/mongod.log && /wait.sh localhost:27017 && npm run _bdd
