version: '2'
services:
  bdd:
    build:
      context: .
      dockerfile: Dockerfile_bdd_test
    links:
      - 'rabbitBdd'
      - 'redisBdd'
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_HOSTNAME=rabbitBdd
      - MONGO=mongodb://localhost:27017/runnable_test
      - REDIS_IPADDRESS=redisBdd
  unit:
    build:
      context: .
      dockerfile: Dockerfile_unit_test
    links:
      - 'redisUnit'
    environment:
      - REDIS_IPADDRESS=redisUnit
  rabbitBdd:
    image: rabbitmq:3.4.3-management
  redisBdd:
    image: redis:3.2
  redisUnit:
    image: redis:3.2
