// Generated by CoffeeScript 1.6.3
(function() {
  var configs, env, eson, os, path, readConfigs, uuid;

  eson = require('eson');

  os = require('os');

  path = require('path');

  uuid = require('node-uuid');

  env = process.env.NODE_ENV || 'development';

  readConfigs = function(filename) {
    return eson().use(eson.args()).use(eson.env()).use(eson.ms).use(eson.replace('{ROOT_DIR}', path.normalize(__dirname + '/..'))).use(eson.replace('{RAND_NUM}', uuid.v4().split('-')[0])).use(eson.replace('{HOME_DIR}', process.env.HOME)).use(eson.replace('{CURR_DIR}', __dirname + '/../configs')).use(eson.replace('{RAND_DIR}', os.tmpDir() + '/' + uuid.v4())).read(__dirname + '/../configs/' + filename + '.json');
  };

  configs = module.exports = readConfigs(env);

  module.exports.readConfigs = readConfigs;

}).call(this);

/*
//@ sourceMappingURL=configs.map
*/
