// Generated by CoffeeScript 1.6.3
(function() {
  var configs, dockerExp, domain;

  configs = require('./configs');

  domain = require('domain');

  dockerExp = /^HTTP response code is (\d\d\d) which indicates an error: (.+)$/;

  module.exports = function(parentDomain) {
    return function(req, res, next) {
      var d;
      d = domain.create();
      req.domain = d;
      if (parentDomain) {
        parentDomain.add(d);
        req.parentDomain = parentDomain;
      }
      d.add(req);
      d.add(res);
      d.on('error', function(e) {
        var code, message, parts;
        if (parentDomain && configs.throwErrors) {
          console.log(e.stack);
          throw e;
        } else if (e.message && dockerExp.test(e.message)) {
          parts = dockerExp.exec(e.message);
          code = parts[1];
          message = parts[2];
          if (code >= 500) {
            code = 502;
          }
          return res.json(code, {
            message: message
          });
        } else {
          return next(e);
        }
      });
      return d.run(next);
    };
  };

}).call(this);

/*
//@ sourceMappingURL=domains.map
*/
