// Generated by CoffeeScript 1.6.3
(function () {
  module.exports = function (code, msg) {
    return {
      code: code,
      msg: msg
    };
  };
}.call(this));  /*
//@ sourceMappingURL=error.map
*/